### ISSUE TITLE
Disabled tile color is not the same as the active tile color.

### ISSUE THREAD

**Issue by anishbajpai014** [haruue/WADB#1]
Quick setting tiles are automatically tinted by the system according to their state for consistency across all apps. Hence it is required that the disabled tile is the same color as the enabled tile.

**Comment by haruue** [comment]
So we should set it to white? I just copied this file from the repo of CyanogenMod. 
https://github.com/haruue/WADB/blob/d242b9bebe09e427abfc6416533dcf5be39d5825/app/src/main/res/drawable/ic_qs_network_adb_off.xml#L26

**Comment by anishbajpai014** [comment]
Yes. It should be white. I have already created a PR.

**Comment by haruue** [comment]
Thx, we will release a new version soon...
